# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a36fb3972d8536148c66c53222af52e18173aa6b0814cf75043c0c0a491234d0db42e93ba9e4eeb663c4eebb83679c5f9846521327324282a2b033e99f387169

test:
  secret_key_base: 4b0224f9e7ea4939bd6d50cee631dc5cf1c54626c6d26754cf2d71c0c2852b9a79e6885b749dd1dc43a2912e6a9eff718b42255c944c8f50946fbdc077b95746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
